//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Block_Blast.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Block_Blast.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTO.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀ TAGASI.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parim combo.
        /// </summary>
        internal static string best_combo {
            get {
                return ResourceManager.GetString("best_combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lauake on puhas!.
        /// </summary>
        internal static string board_clear {
            get {
                return ResourceManager.GetString("board_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värvikas.
        /// </summary>
        internal static string colorful {
            get {
                return ResourceManager.GetString("colorful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBO.
        /// </summary>
        internal static string combo1 {
            get {
                return ResourceManager.GetString("combo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tume.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontolt väljuda ja mängijat vahetada?.
        /// </summary>
        internal static string eaasp {
            get {
                return ResourceManager.GetString("eaasp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;LIHTNE&quot;.
        /// </summary>
        internal static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SISESTA OMA NIMI.
        /// </summary>
        internal static string enter_your_name {
            get {
                return ResourceManager.GetString("enter_your_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIGA.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÄLJU.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mäng Läbi.
        /// </summary>
        internal static string gameover {
            get {
                return ResourceManager.GetString("gameover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;RASKE&quot;.
        /// </summary>
        internal static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEEL.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valgus.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string lines {
            get {
                return ResourceManager.GetString("lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SISSE.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÄLJUMINE.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menüü.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisesta oma mängija nimi, et alustada..
        /// </summary>
        internal static string name_start {
            get {
                return ResourceManager.GetString("name_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ei.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIME PUUDUMINE.
        /// </summary>
        internal static string no_name {
            get {
                return ResourceManager.GetString("no_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulemusi pole.
        /// </summary>
        internal static string no_scores_yet {
            get {
                return ResourceManager.GetString("no_scores_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÄNGI.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mängi Uuesti.
        /// </summary>
        internal static string playagain {
            get {
                return ResourceManager.GetString("playagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mängija.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKOOR.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punktid.
        /// </summary>
        internal static string scores {
            get {
                return ResourceManager.GetString("scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEADED.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALUSTA.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEEMA.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jah.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seda tuleb teha vaid üks kord..
        /// </summary>
        internal static string you_once {
            get {
                return ResourceManager.GetString("you_once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinu nimi ....
        /// </summary>
        internal static string your_name {
            get {
                return ResourceManager.GetString("your_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinu tulemus.
        /// </summary>
        internal static string yoursroce {
            get {
                return ResourceManager.GetString("yoursroce", resourceCulture);
            }
        }
    }
}
